use crate::AppState;
use std::{path::PathBuf, sync::Arc};
use uuid::Uuid;

// ── Public entry point ────────────────────────────────────────────────────────

/// Issue (or renew) a Let's Encrypt certificate for `domain` and `www.domain`.
///
/// Supports:
///   - "http-01"  — writes challenge file to webroot; works for any publicly reachable site
///   - "dns-01"   — requires DNS API integration (Pro); handles wildcard certs
///
/// On success:
///   - cert + key written to /etc/orbitcp/ssl/DOMAIN/
///   - ssl_certs table updated (status='active', expires_at, paths)
///   - "install_ssl" job queued so orbit-agent wires the cert into the vhost
pub async fn issue_certificate(
    state: &Arc<AppState>,
    site_id: Uuid,
    domain: &str,
    challenge_type: &str,
) -> anyhow::Result<()> {
    tracing::info!(site_id = %site_id, domain = %domain, challenge = %challenge_type, "Starting ACME cert issuance");

    // Validate challenge type
    anyhow::ensure!(
        matches!(challenge_type, "http-01" | "dns-01"),
        "Unsupported challenge type: {}",
        challenge_type
    );

    // Resolve ACME directory URL (staging vs production)
    let acme_url = &state.config.acme_directory;

    match challenge_type {
        "http-01" => issue_http01(state, site_id, domain, acme_url).await,
        "dns-01"  => issue_dns01(state, site_id, domain, acme_url).await,
        _         => unreachable!(),
    }
}

// ── HTTP-01 flow ──────────────────────────────────────────────────────────────

async fn issue_http01(
    state: &Arc<AppState>,
    site_id: Uuid,
    domain: &str,
    acme_url: &str,
) -> anyhow::Result<()> {
    use instant_acme::{
        Account, ChallengeType, Identifier, NewAccount, NewOrder, OrderStatus,
    };

    // ── 1. Load or create ACME account ──────────────────────────────────────

    let account = load_or_create_account(acme_url, &state.config.admin_email).await?;

    // ── 2. Create order for domain ───────────────────────────────────────────
    // We issue for the apex domain only. Tunneled/proxied setups frequently
    // can't serve HTTP-01 for www without extra configuration, so including
    // www here would silently invalidate the whole order.

    let identifiers = vec![Identifier::Dns(domain.to_string())];

    let mut order = account
        .new_order(&NewOrder { identifiers: &identifiers })
        .await
        .map_err(|e| anyhow::anyhow!("ACME new_order failed: {}", e))?;

    // ── 3. Get HTTP-01 challenges ────────────────────────────────────────────

    let authorizations = order
        .authorizations()
        .await
        .map_err(|e| anyhow::anyhow!("ACME authorizations failed: {}", e))?;

    let mut challenges_to_complete = Vec::new();

    for authz in &authorizations {
        let challenge = authz
            .challenges
            .iter()
            .find(|c| c.r#type == ChallengeType::Http01)
            .ok_or_else(|| anyhow::anyhow!("No HTTP-01 challenge found for {}", domain))?;

        let token    = challenge.token.as_str();
        let key_auth = order.key_authorization(challenge);

        // ── 4. Write challenge file ──────────────────────────────────────────

        // Validate the token is safe to use as a filename: ACME tokens are
        // base64url-encoded strings (alphanumeric + - _), but we verify this
        // explicitly to prevent path traversal if the ACME server misbehaves.
        anyhow::ensure!(
            !token.is_empty()
                && token.len() <= 128
                && token.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
                && !token.contains(".."),
            "ACME token '{}' contains unsafe characters",
            token
        );

        // NOTE: The nginx vhost generated by provisioning.rs already contains:
        //   location ^~ /.well-known/acme-challenge/ {
        //       root /var/lib/orbitcp/acme/DOMAIN;
        //       try_files $uri =404;
        //   }
        // so challenge files written here are automatically served. No additional
        // nginx config change is required for HTTP-01 to work.

        let challenge_dir = PathBuf::from(format!(
            "/var/lib/orbitcp/acme/{}/.well-known/acme-challenge",
            domain
        ));
        std::fs::create_dir_all(&challenge_dir)
            .map_err(|e| anyhow::anyhow!("create challenge dir failed: {}", e))?;

        let challenge_path = challenge_dir.join(token);
        std::fs::write(&challenge_path, key_auth.as_str())
            .map_err(|e| anyhow::anyhow!("write challenge file failed: {}", e))?;

        // Set correct permissions (nginx/apache must be able to serve this)
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&challenge_path, std::fs::Permissions::from_mode(0o644))
                .ok();
        }

        tracing::debug!(token = %token, "Challenge file written");
        challenges_to_complete.push(challenge.url.clone());
    }

    // ── 5. Tell ACME server challenges are ready ─────────────────────────────

    for challenge_url in &challenges_to_complete {
        order
            .set_challenge_ready(challenge_url)
            .await
            .map_err(|e| anyhow::anyhow!("set_challenge_ready failed: {}", e))?;
    }

    // ── 6. Poll for order to become Ready ────────────────────────────────────

    let deadline = tokio::time::Instant::now() + std::time::Duration::from_secs(120);

    loop {
        if tokio::time::Instant::now() >= deadline {
            anyhow::bail!("ACME order timed out after 120s for {}", domain);
        }

        tokio::time::sleep(std::time::Duration::from_secs(3)).await;

        let state_now = order
            .refresh()
            .await
            .map_err(|e| anyhow::anyhow!("order refresh failed: {}", e))?;

        match state_now.status {
            OrderStatus::Ready => break,
            OrderStatus::Invalid => {
                let err_detail = state_now.error.as_ref()
                    .map(|e| format!(" — LE error: {} ({})",
                        e.detail.as_deref().unwrap_or("unknown"),
                        e.r#type.as_deref().unwrap_or("unknown")))
                    .unwrap_or_default();
                anyhow::bail!("ACME order is invalid for {}{}", domain, err_detail)
            },
            OrderStatus::Valid   => break, // already finalized somehow
            _                   => continue,
        }
    }

    // ── 7. Generate CSR + private key, finalize order ────────────────────────

    let mut params = rcgen::CertificateParams::new(vec![domain.to_string()])
        .map_err(|e| anyhow::anyhow!("rcgen CertificateParams failed: {}", e))?;
    params.distinguished_name = rcgen::DistinguishedName::new();

    let key_pair = rcgen::KeyPair::generate()
        .map_err(|e| anyhow::anyhow!("rcgen KeyPair::generate failed: {}", e))?;
    let csr = params.serialize_request(&key_pair)
        .map_err(|e| anyhow::anyhow!("rcgen serialize_request failed: {}", e))?;

    let csr_der = csr.der().to_vec();

    order
        .finalize(&csr_der)
        .await
        .map_err(|e| anyhow::anyhow!("ACME finalize failed: {}", e))?;

    // ── 8. Retrieve the certificate chain ────────────────────────────────────

    let cert_chain_pem = loop {
        tokio::time::sleep(std::time::Duration::from_secs(2)).await;

        match order.certificate().await {
            Ok(Some(pem)) => break pem,
            Ok(None)      => continue,
            Err(e)        => anyhow::bail!("ACME certificate retrieval failed: {}", e),
        }
    };

    // ── 9. Write cert + key to disk ──────────────────────────────────────────

    let ssl_dir = PathBuf::from(format!("/etc/orbitcp/ssl/{}", domain));
    std::fs::create_dir_all(&ssl_dir)
        .map_err(|e| anyhow::anyhow!("create ssl dir failed: {}", e))?;

    // Secure the directory so only root can list/read it (key lives inside).
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&ssl_dir, std::fs::Permissions::from_mode(0o700))
            .map_err(|e| anyhow::anyhow!("chmod ssl dir failed: {}", e))?;
    }

    let cert_path = ssl_dir.join("cert.pem");
    let key_path  = ssl_dir.join("key.pem");

    // Write certificate chain (0644 — readable by nginx/apache)
    std::fs::write(&cert_path, &cert_chain_pem)
        .map_err(|e| anyhow::anyhow!("write cert.pem failed: {}", e))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&cert_path, std::fs::Permissions::from_mode(0o644))
            .map_err(|e| anyhow::anyhow!("chmod cert.pem failed: {}", e))?;
    }

    // Write private key (0600 — root-only)
    let key_pem = key_pair.serialize_pem();
    std::fs::write(&key_path, &key_pem)
        .map_err(|e| anyhow::anyhow!("write key.pem failed: {}", e))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&key_path, std::fs::Permissions::from_mode(0o600))
            .map_err(|e| anyhow::anyhow!("chmod key.pem failed: {}", e))?;
    }

    tracing::info!(domain = %domain, cert = %cert_path.display(), "Certificate written");

    // Parse expiry date from the PEM so we can store it in the DB
    let expires_at = parse_cert_expiry(&cert_chain_pem).unwrap_or_else(|| {
        // Default to 90 days from now (Let's Encrypt standard)
        chrono::Utc::now() + chrono::Duration::days(90)
    });

    // ── 10. Queue install_ssl job ─────────────────────────────────────────────

    {
        use redis::AsyncCommands;
        let job = serde_json::json!({
            "type":      "install_ssl",
            "site_id":   site_id,
            "domain":    domain,
            "cert_path": cert_path.display().to_string(),
            "key_path":  key_path.display().to_string(),
        });
        let mut conn = state.valkey.clone();
        let _: () = conn.lpush("orbit:jobs", job.to_string()).await.unwrap_or(());
    }

    // ── 11. Update ssl_certs table ────────────────────────────────────────────

    upsert_ssl_cert(
        state,
        site_id,
        domain,
        "active",
        expires_at,
        cert_path.display().to_string(),
        key_path.display().to_string(),
    )
    .await?;

    // Clean up challenge files
    let _ = std::fs::remove_dir_all(format!("/var/lib/orbitcp/acme/{}", domain));

    tracing::info!(site_id = %site_id, domain = %domain, expires = %expires_at, "SSL cert issued");
    Ok(())
}

// ── DNS-01 flow ───────────────────────────────────────────────────────────────

async fn issue_dns01(
    state: &Arc<AppState>,
    site_id: Uuid,
    domain: &str,
    acme_url: &str,
) -> anyhow::Result<()> {
    use instant_acme::{
        Account, ChallengeType, Identifier, NewAccount, NewOrder, OrderStatus,
    };

    anyhow::ensure!(
        state.config.is_pro(),
        "DNS-01 challenge (wildcard certs) requires OrbitCP Pro"
    );

    let account = load_or_create_account(acme_url, &state.config.admin_email).await?;

    let wildcard = format!("*.{}", domain);
    let identifiers = vec![
        Identifier::Dns(domain.to_string()),
        Identifier::Dns(wildcard.clone()),
    ];

    let mut order = account
        .new_order(&NewOrder { identifiers: &identifiers })
        .await
        .map_err(|e| anyhow::anyhow!("ACME new_order (dns-01) failed: {}", e))?;

    let authorizations = order
        .authorizations()
        .await
        .map_err(|e| anyhow::anyhow!("ACME authorizations failed: {}", e))?;

    for authz in &authorizations {
        let challenge = authz
            .challenges
            .iter()
            .find(|c| c.r#type == ChallengeType::Dns01)
            .ok_or_else(|| anyhow::anyhow!("No DNS-01 challenge found"))?;

        let key_auth  = order.key_authorization(challenge);
        let dns_value = key_auth.dns_value();
        let acme_name = format!("_acme-challenge.{}", domain);

        // Write TXT record via orbit-dns PowerDNS API
        set_acme_dns_record(state, &acme_name, &dns_value).await?;

        order
            .set_challenge_ready(&challenge.url)
            .await
            .map_err(|e| anyhow::anyhow!("set_challenge_ready failed: {}", e))?;
    }

    // Poll for ready
    let deadline = tokio::time::Instant::now() + std::time::Duration::from_secs(300);
    loop {
        if tokio::time::Instant::now() >= deadline {
            anyhow::bail!("ACME DNS-01 order timed out after 300s");
        }
        tokio::time::sleep(std::time::Duration::from_secs(5)).await;
        match order.refresh().await.map_err(|e| anyhow::anyhow!("{}", e))?.status {
            OrderStatus::Ready | OrderStatus::Valid => break,
            OrderStatus::Invalid => anyhow::bail!("ACME DNS-01 order invalid"),
            _                    => continue,
        }
    }

    // Generate + finalize
    let mut params = rcgen::CertificateParams::new(vec![
        domain.to_string(),
        wildcard,
    ])
    .map_err(|e| anyhow::anyhow!("rcgen params failed: {}", e))?;
    params.distinguished_name = rcgen::DistinguishedName::new();

    let key_pair = rcgen::KeyPair::generate()
        .map_err(|e| anyhow::anyhow!("rcgen KeyPair::generate failed: {}", e))?;
    let csr = params.serialize_request(&key_pair)
        .map_err(|e| anyhow::anyhow!("rcgen serialize_request failed: {}", e))?;
    let csr_der = csr.der().to_vec();

    order.finalize(&csr_der).await
        .map_err(|e| anyhow::anyhow!("finalize failed: {}", e))?;

    let cert_chain_pem = loop {
        tokio::time::sleep(std::time::Duration::from_secs(2)).await;
        match order.certificate().await {
            Ok(Some(pem)) => break pem,
            Ok(None)      => continue,
            Err(e)        => anyhow::bail!("certificate retrieval failed: {}", e),
        }
    };

    let ssl_dir   = PathBuf::from(format!("/etc/orbitcp/ssl/{}", domain));
    std::fs::create_dir_all(&ssl_dir)?;

    // Secure the ssl directory so only root can access it.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&ssl_dir, std::fs::Permissions::from_mode(0o700))?;
    }

    let cert_path = ssl_dir.join("cert.pem");
    let key_path  = ssl_dir.join("key.pem");

    std::fs::write(&cert_path, &cert_chain_pem)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&cert_path, std::fs::Permissions::from_mode(0o644))?;
    }
    // Write private key THEN set permissions (avoid race where key is readable for a moment).
    std::fs::write(&key_path, key_pair.serialize_pem())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&key_path,  std::fs::Permissions::from_mode(0o600))?;
    }

    let expires_at = parse_cert_expiry(&cert_chain_pem)
        .unwrap_or_else(|| chrono::Utc::now() + chrono::Duration::days(90));

    {
        use redis::AsyncCommands;
        let job = serde_json::json!({
            "type": "install_ssl",
            "site_id": site_id,
            "domain": domain,
            "cert_path": cert_path.display().to_string(),
            "key_path":  key_path.display().to_string(),
        });
        let mut conn = state.valkey.clone();
        let _: () = conn.lpush("orbit:jobs", job.to_string()).await.unwrap_or(());
    }

    upsert_ssl_cert(state, site_id, domain, "active", expires_at,
        cert_path.display().to_string(), key_path.display().to_string()).await?;

    // FIXME: Clean up the _acme-challenge TXT record after validation.
    // orbit-dns should expose a DELETE endpoint; call it here with the same
    // `acme_name` used in `set_acme_dns_record` to avoid leaving stale TXT
    // records in the zone.  Until implemented, TXT records accumulate on
    // each renewal cycle.
    // Example call to add:
    //   delete_acme_dns_record(state, &format!("_acme-challenge.{}", domain)).await;

    tracing::info!(site_id = %site_id, domain = %domain, "Wildcard SSL cert issued (DNS-01)");
    Ok(())
}

// ── Install SSL (update nginx vhost with real TLS block) ──────────────────────

/// Update the nginx vhost for `domain` to serve on port 443 with the supplied
/// certificate and redirect HTTP → HTTPS.
///
/// `unix_user` is the site's OS user (e.g. `orbit_abc123`) and is required to
/// construct the correct PHP-FPM socket path (`/run/php/fpm-{unix_user}.sock`).
/// Previously this was incorrectly derived from the domain name, which produced
/// the wrong socket path for all sites.
///
/// # Callers
/// Update `dispatch_install_ssl` in jobs.rs whenever changing this signature —
/// the `unix_user` field must be included in `install_ssl` job payloads.
pub async fn install_ssl_vhost(
    state: &Arc<AppState>,
    domain: &str,
    cert_path: &str,
    key_path: &str,
) -> anyhow::Result<()> {
    // Fetch the site's unix_user from the database so we can build the correct
    // PHP-FPM socket path.  The job payload carries domain; look up by domain.
    let row = sqlx::query!(
        "SELECT unix_user FROM sites WHERE domain = $1 AND deleted_at IS NULL LIMIT 1",
        domain
    )
    .fetch_optional(&state.db)
    .await
    .map_err(|e| anyhow::anyhow!("install_ssl_vhost: DB lookup for domain {} failed: {}", domain, e))?;

    let unix_user = row
        .map(|r| r.unix_user)
        .unwrap_or_else(|| {
            // Fallback: best-effort derive.  This is wrong for multi-word users but
            // prevents a hard crash if the site row was deleted between job enqueue and run.
            tracing::warn!(domain = %domain, "install_ssl_vhost: site not found in DB; unix_user unknown");
            String::new()
        });

    // Validate domain for path safety before embedding in file paths.
    anyhow::ensure!(
        !domain.contains('/') && !domain.contains(".."),
        "install_ssl_vhost: domain contains path traversal chars: {}",
        domain
    );

    let fpm_socket = if unix_user.is_empty() {
        // FIXME: unix_user could not be determined — the PHP location block will be
        // broken.  Operator must manually update /etc/nginx/sites-available/{domain}.conf.
        String::from("/run/php/fpm-UNKNOWN.sock")
    } else {
        format!("/run/php/fpm-{}.sock", unix_user)
    };

    let tls_block = format!(
        "# OrbitCP auto-generated TLS vhost for {domain}\n\
         server {{\n\
             listen 443 ssl http2;\n\
             listen [::]:443 ssl http2;\n\
             server_name {domain} www.{domain};\n\
             root /home/{user}/public_html;\n\
             index index.php index.html;\n\
         \n\
             ssl_certificate     {cert};\n\
             ssl_certificate_key {key};\n\
             ssl_protocols       TLSv1.2 TLSv1.3;\n\
             ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:\
         ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;\n\
             ssl_prefer_server_ciphers off;\n\
             ssl_session_cache   shared:SSL:10m;\n\
             ssl_session_timeout 10m;\n\
             ssl_stapling        on;\n\
             ssl_stapling_verify on;\n\
         \n\
             add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains; preload\" always;\n\
         \n\
             location / {{\n\
                 try_files $uri $uri/ /index.php?$query_string;\n\
             }}\n\
         \n\
             location ~ \\.php$ {{\n\
                 include       snippets/fastcgi-php.conf;\n\
                 fastcgi_pass  unix:{fpm_socket};\n\
                 fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;\n\
                 include       fastcgi_params;\n\
             }}\n\
         \n\
             location ~ /\\. {{ deny all; return 404; }}\n\
         }}\n\
         \n\
         # HTTP → HTTPS redirect\n\
         server {{\n\
             listen 80;\n\
             server_name {domain} www.{domain};\n\
             return 301 https://$host$request_uri;\n\
         }}\n",
        domain     = domain,
        user       = unix_user,
        fpm_socket = fpm_socket,
        cert       = cert_path,
        key        = key_path,
    );

    let vhost_path = format!("/etc/nginx/sites-available/{}.conf", domain);
    std::fs::write(&vhost_path, tls_block)
        .map_err(|e| anyhow::anyhow!("write TLS vhost failed: {}", e))?;

    // nginx -t then reload
    let test = std::process::Command::new("nginx").arg("-t").output()?;
    anyhow::ensure!(test.status.success(),
        "nginx -t failed: {}", String::from_utf8_lossy(&test.stderr));

    let reload = std::process::Command::new("systemctl").args(["reload", "nginx"]).output()?;
    anyhow::ensure!(reload.status.success(), "systemctl reload nginx failed");

    Ok(())
}

// ── ACME account management ───────────────────────────────────────────────────

async fn load_or_create_account(acme_url: &str, admin_email: &str) -> anyhow::Result<instant_acme::Account> {
    use instant_acme::{Account, NewAccount};

    let account_path = "/etc/orbitcp/acme/account.json";

    if std::path::Path::new(account_path).exists() {
        let data = std::fs::read_to_string(account_path)
            .map_err(|e| anyhow::anyhow!("read ACME account failed: {}", e))?;

        let credentials: instant_acme::AccountCredentials = serde_json::from_str(&data)
            .map_err(|e| anyhow::anyhow!("parse ACME account failed: {}", e))?;

        let account = Account::from_credentials(credentials)
            .await
            .map_err(|e| anyhow::anyhow!("restore ACME account failed: {}", e))?;

        return Ok(account);
    }

    // Create new account
    std::fs::create_dir_all("/etc/orbitcp/acme")
        .map_err(|e| anyhow::anyhow!("create ACME dir failed: {}", e))?;

    let contact = format!("mailto:{}", admin_email);
    let (account, credentials) = Account::create(
        &NewAccount {
            contact:                  &[&contact],
            terms_of_service_agreed:  true,
            only_return_existing:     false,
        },
        acme_url,
        None,
    )
    .await
    .map_err(|e| anyhow::anyhow!("ACME account create failed: {}", e))?;

    let json = serde_json::to_string_pretty(&credentials)
        .map_err(|e| anyhow::anyhow!("serialize ACME credentials failed: {}", e))?;

    std::fs::write(account_path, &json)
        .map_err(|e| anyhow::anyhow!("write ACME account failed: {}", e))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(account_path, std::fs::Permissions::from_mode(0o600)).ok();
    }

    tracing::info!("ACME account created and saved");
    Ok(account)
}

// ── DNS-01 helper: set TXT record via orbit-dns ───────────────────────────────

async fn set_acme_dns_record(
    state: &Arc<AppState>,
    name: &str,
    value: &str,
) -> anyhow::Result<()> {
    // orbit-dns listens on localhost:2053 with a REST API
    let dns_url = format!("http://127.0.0.1:2053/api/v1/dns/records");

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()?;

    let body = serde_json::json!({
        "name":    name,
        "type":    "TXT",
        "ttl":     60,
        "content": value,
    });

    let resp = client
        .post(&dns_url)
        .json(&body)
        .send()
        .await
        .map_err(|e| anyhow::anyhow!("orbit-dns TXT record set failed: {}", e))?;

    anyhow::ensure!(
        resp.status().is_success(),
        "orbit-dns returned {} for TXT record set",
        resp.status()
    );

    // Wait for propagation (minimum TTL is 60s; Let's Encrypt will retry)
    tokio::time::sleep(std::time::Duration::from_secs(5)).await;
    Ok(())
}

// ── DB helpers ────────────────────────────────────────────────────────────────

async fn upsert_ssl_cert(
    state:      &Arc<AppState>,
    site_id:    Uuid,
    domain:     &str,
    status:     &str,
    expires_at: chrono::DateTime<chrono::Utc>,
    cert_path:  String,
    key_path:   String,
) -> anyhow::Result<()> {
    sqlx::query!(
        r#"INSERT INTO ssl_certs (id, site_id, domain, status, expires_at, cert_path, key_path, issued_at, created_at)
           VALUES ($1, $2, $3, $4::text::ssl_cert_status, $5, $6, $7, NOW(), NOW())
           ON CONFLICT (site_id)
           DO UPDATE SET
               status     = EXCLUDED.status,
               expires_at = EXCLUDED.expires_at,
               cert_path  = EXCLUDED.cert_path,
               key_path   = EXCLUDED.key_path,
               issued_at  = NOW(),
               updated_at = NOW()"#,
        Uuid::new_v4(),
        site_id,
        domain,
        status as &str,
        expires_at,
        cert_path,
        key_path,
    )
    .execute(&state.db)
    .await
    .map_err(|e| anyhow::anyhow!("ssl_certs upsert failed: {}", e))?;

    Ok(())
}

// ── Certificate parsing ───────────────────────────────────────────────────────

/// Parse the expiry date from the first PEM certificate in a chain.
/// Returns None if parsing fails (caller falls back to 90 days from now).
fn parse_cert_expiry(pem: &str) -> Option<chrono::DateTime<chrono::Utc>> {
    use x509_parser::prelude::*;

    // Extract the base64 body from the first -----BEGIN CERTIFICATE----- block
    let start = pem.find("-----BEGIN CERTIFICATE-----")?;
    let end   = pem[start..].find("-----END CERTIFICATE-----")?;
    let body  = &pem[start + 27 .. start + end].replace('\n', "");

    let der = base64::Engine::decode(&base64::engine::general_purpose::STANDARD, body).ok()?;

    // Parse the DER-encoded certificate and extract the notAfter validity field.
    let (_, cert) = X509Certificate::from_der(&der).ok()?;
    let not_after = cert.tbs_certificate.validity.not_after.to_datetime();
    chrono::DateTime::<chrono::Utc>::from_timestamp(not_after.unix_timestamp(), 0)
}

// ── Auto-renewal job ──────────────────────────────────────────────────────────

/// Called by the cron service daily.  Queues "issue_ssl" for certs expiring within 30 days.
pub async fn renew_expiring_certs(state: &Arc<AppState>) -> anyhow::Result<()> {
    let expiring = sqlx::query!(
        r#"SELECT sc.site_id, sc.domain, s.status::text AS site_status
           FROM ssl_certs sc
           JOIN sites s ON s.id = sc.site_id
           WHERE sc.status = 'active'
             AND sc.expires_at < NOW() + INTERVAL '30 days'
             AND s.status = 'active'
             AND s.deleted_at IS NULL"#
    )
    .fetch_all(&state.db)
    .await?;

    tracing::info!(count = expiring.len(), "SSL renewal check: {} certs expiring soon", expiring.len());

    for cert in expiring {
        use redis::AsyncCommands;
        let job = serde_json::json!({
            "type":      "issue_ssl",
            "site_id":   cert.site_id,
            "domain":    cert.domain,
            "challenge": "http-01",
        });
        let mut conn = state.valkey.clone();
        let _: () = conn.lpush("orbit:jobs", job.to_string()).await.unwrap_or(());
        tracing::info!(domain = %cert.domain, "Queued SSL renewal");
    }

    Ok(())
}
