[workspace]
resolver = "2"
members = [
    "orbit-panel",
    "orbit-agent",
    "orbit-dns",
    "orbit-mail",
    "orbit-cron",
    "orbit-cli",
    "orbit-mcp",
]

[workspace.dependencies]
axum           = { version = "0.8", features = ["ws", "multipart"] }
tokio          = { version = "1", features = ["full"] }
sqlx           = { version = "0.8", features = ["runtime-tokio", "postgres", "macros", "migrate", "uuid", "chrono", "json", "rust_decimal", "ipnetwork"] }
serde          = { version = "1", features = ["derive"] }
serde_json     = "1"
tonic          = { version = "0.12", features = ["tls"] }
prost          = "0.13"
tower          = "0.5"
tower-http     = { version = "0.6", features = ["cors", "trace", "compression-gzip", "request-id"] }
tower_governor = "0.7"
metrics        = "0.23"
metrics-exporter-prometheus = { version = "0.15", default-features = false }
tracing        = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
anyhow         = "1"
thiserror      = "1"
uuid           = { version = "1", features = ["v4", "serde"] }
chrono         = { version = "0.4", features = ["serde"] }
jsonwebtoken   = "9"
totp-rs        = "5"
argon2         = "0.5"
instant-acme   = "0.7"
reqwest        = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
rustls         = { version = "0.23", features = ["aws-lc-rs"] }
futures-util   = "0.3"
tokio-stream   = "0.1"
tokio-util     = { version = "0.7", features = ["io"] }
bytes          = "1"
rand           = "0.8"
base64         = "0.22"
sha2           = "0.10"
hex            = "0.4"
regex          = "1"
handlebars     = "6"
config         = "0.14"
dotenvy        = "0.15"
once_cell      = "1"
redis          = { version = "0.25", features = ["tokio-comp", "connection-manager"] }
rust_decimal   = { version = "1", features = ["serde-with-str"] }
async-trait    = "0.1"
